### ISSUE TITLE
Knowls not loading

### ISSUE THREAD

**Issue by nelong** [active-calculus/active-calculus-vector#21]
@mitchkeller  I think you have a fix for this and wanted to check. 
Knowls are loading empty in most settings for me. I don't remember what the cause of this is or if there is a general fix. 
Let me know if you know what to do.

**Comment by mitchkeller** [comment]
The knowls that load something whose original location is elsewhere in the book (so an `xref` to a figure or theorem, for instance) will show empty when viewing as a file. Knowls for things born there (solution to an example, for instance) will show up fine. You need to run ` python3 -m http.server --bind 127.0.0.1` in your HTML output directory (or just `python` if your system `python` is a python 3 instance). Then you can go to `http://localhost:8000` in your browser. If you want to use a port other than 8000, insert it before the `--bind 127.0.0.1` portion of the command.

**Comment by nelong** [comment]
So that works great for one instance of PreTeXt. I'm working at three ptx projects right now. Do I use a different port for each project so that I can access each of these separately?

**Comment by mitchkeller** [comment]
Yup! When I was looking at both my branch and yours, I had mine on port 8000 and yours on 6565.

**Comment by nelong** [comment]
In reading your answer, so much of the backend server stuff made sense. I
have no idea why I didn't put stuff together but I feel like I'm "getting"
it now.

**Comment by mitchkeller** [comment]
Closing this, since it's resolved. Will continue to exist in the closed issues in case that python one-liner needs to be found again.
