### ISSUE TITLE
S_Vector_Div needs Summary

### ISSUE THREAD

**Issue by mitchkeller** [active-calculus/active-calculus-vector#23]
@nelong The summary that is currently in S_Vector_Div is the summary from the first section. We need to write a summary here, preferably by answering the motivating questions in the objectives (and perhaps restructuring those questions if need be to make them connect nicely to a section summary).

**Comment by nelong** [comment]
@mitchkeller I have updated the summary of that section to reflect answers to the motivating questions (in terms of the exposition of the section). Please let me know if you need anything else.

**Comment by mitchkeller** [comment]
Thanks. Was able to pull back down to my local machine smoothly.
