### ISSUE TITLE
Punctuation for title

### ISSUE THREAD

**Issue by mitchkeller** [active-calculus/active-calculus-vector#29]
@davidfarmer suggests "Active Calculus: Multivariable + Vector" as better than the current "Active Calculus - Multivariable + Vector". That's likely better, so make a decision on updating before building any new versions for posting.

**Comment by nelong** [comment]
@mitchkeller Has this issue taken care of itself since there will only be AC:M in a month?

**Comment by mitchkeller** [comment]
Yes, we can close this since we will just use ACM soon.
