### ISSUE TITLE
Adding and Checking HW problems in Chapter 12

### ISSUE THREAD

**Issue by nelong** [active-calculus/active-calculus-vector#43]
This will be the long list of tasks for the addition of homework questions throughout Chapter 12. The guidance will be to use ~8 WebWork Questions and ~4 pencil and paper questions per section. https://webwork.sfasu.edu/webwork2/AC-VectorCalc/ is the WebWork course that we should use to organize the webwork problems. We can subdivide this issue to separate issues if we need more focused commentary on problems by section.

**Comment by nelong** [comment]
I have added problem sets for all sections of Chapter 12 in our sample webwork course. I have added problems to each section that I think could be used. 
I will work now to see which section need other exercises and add some ideas for exercises to be fleshed out later.

**Comment by mitchkeller** [comment]
If I get one file per section with a line for each OPL problem path, I can easily build files we can xi:include for the WW and check for interactive and print formatting.
