### ISSUE TITLE
Exercise typos in 9.4

### ISSUE THREAD

**Issue by mitchkeller** [active-calculus/active-calculus-vector#77]
13(d).  Shouldn't this be "Determine the measure of  \angle QPR so that students can continue working with  \overrightarrow{PQ} \text{ and } \overrightarrow{PR} ?

14. There are two vectors labeled as v.  My students and I assume that the third one in the list is supposed to be labeled w.

https://groups.google.com/d/msgid/active-calculus-multivariable/5644926c-0e17-494f-837d-9e694a52dc37n%40googlegroups.com?utm_medium=email&utm_source=footer

**Comment by nelong** [comment]
Fixed in 2024-Reorganization branch 6a8c30fb commit
